# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\mainWindowForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 653)
        MainWindow.setMinimumSize(QtCore.QSize(1138, 653))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_students = QtWidgets.QWidget()
        self.tab_students.setObjectName("tab_students")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_students)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_students)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_general = QtWidgets.QWidget()
        self.page_general.setObjectName("page_general")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_general)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_head_general = QtWidgets.QLabel(self.page_general)
        self.label_head_general.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.label_head_general.setFont(font)
        self.label_head_general.setObjectName("label_head_general")
        self.horizontalLayout.addWidget(self.label_head_general)
        self.label_update_general = QtWidgets.QLabel(self.page_general)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        self.label_update_general.setFont(font)
        self.label_update_general.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_update_general.setObjectName("label_update_general")
        self.horizontalLayout.addWidget(self.label_update_general)
        self.button_update_general = QtWidgets.QPushButton(self.page_general)
        self.button_update_general.setMinimumSize(QtCore.QSize(111, 30))
        self.button_update_general.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_update_general.setFont(font)
        self.button_update_general.setObjectName("button_update_general")
        self.horizontalLayout.addWidget(self.button_update_general)
        self.button_gen_general = QtWidgets.QPushButton(self.page_general)
        self.button_gen_general.setMinimumSize(QtCore.QSize(111, 30))
        self.button_gen_general.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_gen_general.setFont(font)
        self.button_gen_general.setObjectName("button_gen_general")
        self.horizontalLayout.addWidget(self.button_gen_general)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_edit_search_general = QtWidgets.QLineEdit(self.page_general)
        self.line_edit_search_general.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.line_edit_search_general.setFont(font)
        self.line_edit_search_general.setObjectName("line_edit_search_general")
        self.verticalLayout.addWidget(self.line_edit_search_general)
        self.table_general = QtWidgets.QTableWidget(self.page_general)
        self.table_general.setObjectName("table_general")
        self.table_general.setColumnCount(0)
        self.table_general.setRowCount(0)
        self.verticalLayout.addWidget(self.table_general)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_info_general = QtWidgets.QLabel(self.page_general)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_info_general.setFont(font)
        self.label_info_general.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_info_general.setObjectName("label_info_general")
        self.horizontalLayout_3.addWidget(self.label_info_general)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.button_add_general = QtWidgets.QPushButton(self.page_general)
        self.button_add_general.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_add_general.setFont(font)
        self.button_add_general.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_add_general.setObjectName("button_add_general")
        self.horizontalLayout_3.addWidget(self.button_add_general)
        self.button_edit_general = QtWidgets.QPushButton(self.page_general)
        self.button_edit_general.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_edit_general.setFont(font)
        self.button_edit_general.setObjectName("button_edit_general")
        self.horizontalLayout_3.addWidget(self.button_edit_general)
        self.button_delete_general = QtWidgets.QPushButton(self.page_general)
        self.button_delete_general.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_delete_general.setFont(font)
        self.button_delete_general.setObjectName("button_delete_general")
        self.horizontalLayout_3.addWidget(self.button_delete_general)
        self.button_clear_general = QtWidgets.QPushButton(self.page_general)
        self.button_clear_general.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_clear_general.setFont(font)
        self.button_clear_general.setObjectName("button_clear_general")
        self.horizontalLayout_3.addWidget(self.button_clear_general)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page_general)
        self.page_groups = QtWidgets.QWidget()
        self.page_groups.setObjectName("page_groups")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_groups)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_back_groups = QtWidgets.QPushButton(self.page_groups)
        self.button_back_groups.setMinimumSize(QtCore.QSize(30, 30))
        self.button_back_groups.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_back_groups.setFont(font)
        self.button_back_groups.setObjectName("button_back_groups")
        self.horizontalLayout_6.addWidget(self.button_back_groups)
        self.label_head_groups = QtWidgets.QLabel(self.page_groups)
        self.label_head_groups.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.label_head_groups.setFont(font)
        self.label_head_groups.setObjectName("label_head_groups")
        self.horizontalLayout_6.addWidget(self.label_head_groups)
        self.label_update_groups = QtWidgets.QLabel(self.page_groups)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        self.label_update_groups.setFont(font)
        self.label_update_groups.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_update_groups.setObjectName("label_update_groups")
        self.horizontalLayout_6.addWidget(self.label_update_groups)
        self.button_update_groups = QtWidgets.QPushButton(self.page_groups)
        self.button_update_groups.setMinimumSize(QtCore.QSize(111, 30))
        self.button_update_groups.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_update_groups.setFont(font)
        self.button_update_groups.setObjectName("button_update_groups")
        self.horizontalLayout_6.addWidget(self.button_update_groups)
        self.button_gen_groups = QtWidgets.QPushButton(self.page_groups)
        self.button_gen_groups.setMinimumSize(QtCore.QSize(111, 30))
        self.button_gen_groups.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_gen_groups.setFont(font)
        self.button_gen_groups.setObjectName("button_gen_groups")
        self.horizontalLayout_6.addWidget(self.button_gen_groups)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.line_edit_search_groups = QtWidgets.QLineEdit(self.page_groups)
        self.line_edit_search_groups.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.line_edit_search_groups.setFont(font)
        self.line_edit_search_groups.setObjectName("line_edit_search_groups")
        self.verticalLayout_6.addWidget(self.line_edit_search_groups)
        self.table_groups = QtWidgets.QTableWidget(self.page_groups)
        self.table_groups.setObjectName("table_groups")
        self.table_groups.setColumnCount(0)
        self.table_groups.setRowCount(0)
        self.verticalLayout_6.addWidget(self.table_groups)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_info_groups = QtWidgets.QLabel(self.page_groups)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_info_groups.setFont(font)
        self.label_info_groups.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_info_groups.setObjectName("label_info_groups")
        self.horizontalLayout_2.addWidget(self.label_info_groups)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.button_add_groups = QtWidgets.QPushButton(self.page_groups)
        self.button_add_groups.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_add_groups.setFont(font)
        self.button_add_groups.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_add_groups.setObjectName("button_add_groups")
        self.horizontalLayout_2.addWidget(self.button_add_groups)
        self.button_edit_groups = QtWidgets.QPushButton(self.page_groups)
        self.button_edit_groups.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_edit_groups.setFont(font)
        self.button_edit_groups.setObjectName("button_edit_groups")
        self.horizontalLayout_2.addWidget(self.button_edit_groups)
        self.button_delete_groups = QtWidgets.QPushButton(self.page_groups)
        self.button_delete_groups.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_delete_groups.setFont(font)
        self.button_delete_groups.setObjectName("button_delete_groups")
        self.horizontalLayout_2.addWidget(self.button_delete_groups)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.page_groups)
        self.page_student = QtWidgets.QWidget()
        self.page_student.setObjectName("page_student")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_student)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button_back_student = QtWidgets.QPushButton(self.page_student)
        self.button_back_student.setMinimumSize(QtCore.QSize(30, 30))
        self.button_back_student.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_back_student.setFont(font)
        self.button_back_student.setObjectName("button_back_student")
        self.horizontalLayout_12.addWidget(self.button_back_student)
        self.label_head_student = QtWidgets.QLabel(self.page_student)
        self.label_head_student.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.label_head_student.setFont(font)
        self.label_head_student.setObjectName("label_head_student")
        self.horizontalLayout_12.addWidget(self.label_head_student)
        self.label_update_student = QtWidgets.QLabel(self.page_student)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        self.label_update_student.setFont(font)
        self.label_update_student.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_update_student.setObjectName("label_update_student")
        self.horizontalLayout_12.addWidget(self.label_update_student)
        self.button_update_student = QtWidgets.QPushButton(self.page_student)
        self.button_update_student.setMinimumSize(QtCore.QSize(111, 30))
        self.button_update_student.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_update_student.setFont(font)
        self.button_update_student.setObjectName("button_update_student")
        self.horizontalLayout_12.addWidget(self.button_update_student)
        self.button_gen_student = QtWidgets.QPushButton(self.page_student)
        self.button_gen_student.setMinimumSize(QtCore.QSize(111, 30))
        self.button_gen_student.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_gen_student.setFont(font)
        self.button_gen_student.setObjectName("button_gen_student")
        self.horizontalLayout_12.addWidget(self.button_gen_student)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.line_edit_search_student = QtWidgets.QLineEdit(self.page_student)
        self.line_edit_search_student.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.line_edit_search_student.setFont(font)
        self.line_edit_search_student.setObjectName("line_edit_search_student")
        self.verticalLayout_15.addWidget(self.line_edit_search_student)
        self.table_student = QtWidgets.QTableWidget(self.page_student)
        self.table_student.setObjectName("table_student")
        self.table_student.setColumnCount(0)
        self.table_student.setRowCount(0)
        self.verticalLayout_15.addWidget(self.table_student)
        self.verticalLayout_4.addLayout(self.verticalLayout_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_info_student = QtWidgets.QLabel(self.page_student)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_info_student.setFont(font)
        self.label_info_student.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_info_student.setObjectName("label_info_student")
        self.horizontalLayout_4.addWidget(self.label_info_student)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.button_add_student = QtWidgets.QPushButton(self.page_student)
        self.button_add_student.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_add_student.setFont(font)
        self.button_add_student.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_add_student.setObjectName("button_add_student")
        self.horizontalLayout_4.addWidget(self.button_add_student)
        self.button_delete_student = QtWidgets.QPushButton(self.page_student)
        self.button_delete_student.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_delete_student.setFont(font)
        self.button_delete_student.setObjectName("button_delete_student")
        self.horizontalLayout_4.addWidget(self.button_delete_student)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_student)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_students, "")
        self.tab_disciplines = QtWidgets.QWidget()
        self.tab_disciplines.setObjectName("tab_disciplines")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_disciplines)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab_disciplines)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_disciplines = QtWidgets.QWidget()
        self.page_disciplines.setObjectName("page_disciplines")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_disciplines)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_head_disciplines = QtWidgets.QLabel(self.page_disciplines)
        self.label_head_disciplines.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.label_head_disciplines.setFont(font)
        self.label_head_disciplines.setObjectName("label_head_disciplines")
        self.horizontalLayout_8.addWidget(self.label_head_disciplines)
        self.label_update_disciplines = QtWidgets.QLabel(self.page_disciplines)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        self.label_update_disciplines.setFont(font)
        self.label_update_disciplines.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_update_disciplines.setObjectName("label_update_disciplines")
        self.horizontalLayout_8.addWidget(self.label_update_disciplines)
        self.button_update_disciplines = QtWidgets.QPushButton(self.page_disciplines)
        self.button_update_disciplines.setMinimumSize(QtCore.QSize(111, 30))
        self.button_update_disciplines.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_update_disciplines.setFont(font)
        self.button_update_disciplines.setObjectName("button_update_disciplines")
        self.horizontalLayout_8.addWidget(self.button_update_disciplines)
        self.button_gen_disciplines = QtWidgets.QPushButton(self.page_disciplines)
        self.button_gen_disciplines.setMinimumSize(QtCore.QSize(111, 30))
        self.button_gen_disciplines.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_gen_disciplines.setFont(font)
        self.button_gen_disciplines.setObjectName("button_gen_disciplines")
        self.horizontalLayout_8.addWidget(self.button_gen_disciplines)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.line_edit_search_disciplines = QtWidgets.QLineEdit(self.page_disciplines)
        self.line_edit_search_disciplines.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.line_edit_search_disciplines.setFont(font)
        self.line_edit_search_disciplines.setObjectName("line_edit_search_disciplines")
        self.verticalLayout_9.addWidget(self.line_edit_search_disciplines)
        self.table_disciplines = QtWidgets.QTableWidget(self.page_disciplines)
        self.table_disciplines.setObjectName("table_disciplines")
        self.table_disciplines.setColumnCount(0)
        self.table_disciplines.setRowCount(0)
        self.verticalLayout_9.addWidget(self.table_disciplines)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.button_add_disciplines = QtWidgets.QPushButton(self.page_disciplines)
        self.button_add_disciplines.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_add_disciplines.setFont(font)
        self.button_add_disciplines.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_add_disciplines.setObjectName("button_add_disciplines")
        self.horizontalLayout_5.addWidget(self.button_add_disciplines)
        self.button_edit_disciplines = QtWidgets.QPushButton(self.page_disciplines)
        self.button_edit_disciplines.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_edit_disciplines.setFont(font)
        self.button_edit_disciplines.setObjectName("button_edit_disciplines")
        self.horizontalLayout_5.addWidget(self.button_edit_disciplines)
        self.button_delete_disciplines = QtWidgets.QPushButton(self.page_disciplines)
        self.button_delete_disciplines.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_delete_disciplines.setFont(font)
        self.button_delete_disciplines.setObjectName("button_delete_disciplines")
        self.horizontalLayout_5.addWidget(self.button_delete_disciplines)
        self.button_clear_disciplines = QtWidgets.QPushButton(self.page_disciplines)
        self.button_clear_disciplines.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_clear_disciplines.setFont(font)
        self.button_clear_disciplines.setObjectName("button_clear_disciplines")
        self.horizontalLayout_5.addWidget(self.button_clear_disciplines)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.stackedWidget_2.addWidget(self.page_disciplines)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_disciplines, "")
        self.tab_teachers = QtWidgets.QWidget()
        self.tab_teachers.setObjectName("tab_teachers")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_teachers)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.tab_teachers)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_teachers = QtWidgets.QWidget()
        self.page_teachers.setObjectName("page_teachers")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_teachers)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_head_teachers = QtWidgets.QLabel(self.page_teachers)
        self.label_head_teachers.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.label_head_teachers.setFont(font)
        self.label_head_teachers.setObjectName("label_head_teachers")
        self.horizontalLayout_10.addWidget(self.label_head_teachers)
        self.label_update_teachers = QtWidgets.QLabel(self.page_teachers)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        self.label_update_teachers.setFont(font)
        self.label_update_teachers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_update_teachers.setObjectName("label_update_teachers")
        self.horizontalLayout_10.addWidget(self.label_update_teachers)
        self.button_update_teachers = QtWidgets.QPushButton(self.page_teachers)
        self.button_update_teachers.setMinimumSize(QtCore.QSize(111, 30))
        self.button_update_teachers.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_update_teachers.setFont(font)
        self.button_update_teachers.setObjectName("button_update_teachers")
        self.horizontalLayout_10.addWidget(self.button_update_teachers)
        self.button_gen_teachers = QtWidgets.QPushButton(self.page_teachers)
        self.button_gen_teachers.setMinimumSize(QtCore.QSize(111, 30))
        self.button_gen_teachers.setMaximumSize(QtCore.QSize(111, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_gen_teachers.setFont(font)
        self.button_gen_teachers.setObjectName("button_gen_teachers")
        self.horizontalLayout_10.addWidget(self.button_gen_teachers)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.line_edit_search_teachers = QtWidgets.QLineEdit(self.page_teachers)
        self.line_edit_search_teachers.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.line_edit_search_teachers.setFont(font)
        self.line_edit_search_teachers.setObjectName("line_edit_search_teachers")
        self.verticalLayout_13.addWidget(self.line_edit_search_teachers)
        self.table_teachers = QtWidgets.QTableWidget(self.page_teachers)
        self.table_teachers.setObjectName("table_teachers")
        self.table_teachers.setColumnCount(0)
        self.table_teachers.setRowCount(0)
        self.verticalLayout_13.addWidget(self.table_teachers)
        self.verticalLayout_7.addLayout(self.verticalLayout_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.button_add_teachers = QtWidgets.QPushButton(self.page_teachers)
        self.button_add_teachers.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_add_teachers.setFont(font)
        self.button_add_teachers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_add_teachers.setObjectName("button_add_teachers")
        self.horizontalLayout_7.addWidget(self.button_add_teachers)
        self.button_edit_teachers = QtWidgets.QPushButton(self.page_teachers)
        self.button_edit_teachers.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_edit_teachers.setFont(font)
        self.button_edit_teachers.setObjectName("button_edit_teachers")
        self.horizontalLayout_7.addWidget(self.button_edit_teachers)
        self.button_delete_teachers = QtWidgets.QPushButton(self.page_teachers)
        self.button_delete_teachers.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_delete_teachers.setFont(font)
        self.button_delete_teachers.setObjectName("button_delete_teachers")
        self.horizontalLayout_7.addWidget(self.button_delete_teachers)
        self.button_clear_teachers = QtWidgets.QPushButton(self.page_teachers)
        self.button_clear_teachers.setMinimumSize(QtCore.QSize(141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        self.button_clear_teachers.setFont(font)
        self.button_clear_teachers.setObjectName("button_clear_teachers")
        self.horizontalLayout_7.addWidget(self.button_clear_teachers)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.stackedWidget_3.addWidget(self.page_teachers)
        self.gridLayout_4.addWidget(self.stackedWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_teachers, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_head_general.setText(_translate("MainWindow", "СПИСОК ГРУПП"))
        self.label_update_general.setText(_translate("MainWindow", "ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: %s"))
        self.button_update_general.setText(_translate("MainWindow", "ОБНОВИТЬ"))
        self.button_gen_general.setText(_translate("MainWindow", "ГЕНЕРАЦИЯ"))
        self.label_info_general.setText(_translate("MainWindow", "ДВАЖДЫ НАЖМИТЕ НА ГРУППУ ДЛЯ ПЕРЕХОДА"))
        self.button_add_general.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.button_edit_general.setText(_translate("MainWindow", "ИЗМЕНИТЬ"))
        self.button_delete_general.setText(_translate("MainWindow", "УДАЛИТЬ"))
        self.button_clear_general.setText(_translate("MainWindow", "ОЧИСТИТЬ"))
        self.button_back_groups.setText(_translate("MainWindow", "←"))
        self.label_head_groups.setText(_translate("MainWindow", "ГРУППА %S"))
        self.label_update_groups.setText(_translate("MainWindow", "ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: %s"))
        self.button_update_groups.setText(_translate("MainWindow", "ОБНОВИТЬ"))
        self.button_gen_groups.setText(_translate("MainWindow", "ГЕНЕРАЦИЯ"))
        self.label_info_groups.setText(_translate("MainWindow", "ДВАЖДЫ НАЖМИТЕ НА СТУДЕНТА ДЛЯ ПЕРЕХОДА"))
        self.button_add_groups.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.button_edit_groups.setText(_translate("MainWindow", "ИЗМЕНИТЬ"))
        self.button_delete_groups.setText(_translate("MainWindow", "УДАЛИТЬ"))
        self.button_back_student.setText(_translate("MainWindow", "←"))
        self.label_head_student.setText(_translate("MainWindow", "%S"))
        self.label_update_student.setText(_translate("MainWindow", "ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: %s"))
        self.button_update_student.setText(_translate("MainWindow", "ОБНОВИТЬ"))
        self.button_gen_student.setText(_translate("MainWindow", "ГЕНЕРАЦИЯ"))
        self.label_info_student.setText(_translate("MainWindow", "ДВАЖДЫ НАЖМИТЕ НА ДИСЦИПЛИНУ ДЛЯ ВЫСТАВЛЕНИЯ ОЦЕНКИ"))
        self.button_add_student.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.button_delete_student.setText(_translate("MainWindow", "УДАЛИТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_students), _translate("MainWindow", "СТУДЕНТЫ"))
        self.label_head_disciplines.setText(_translate("MainWindow", "СПИСОК ДИСЦИПЛИН"))
        self.label_update_disciplines.setText(_translate("MainWindow", "ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: %s"))
        self.button_update_disciplines.setText(_translate("MainWindow", "ОБНОВИТЬ"))
        self.button_gen_disciplines.setText(_translate("MainWindow", "ГЕНЕРАЦИЯ"))
        self.button_add_disciplines.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.button_edit_disciplines.setText(_translate("MainWindow", "ИЗМЕНИТЬ"))
        self.button_delete_disciplines.setText(_translate("MainWindow", "УДАЛИТЬ"))
        self.button_clear_disciplines.setText(_translate("MainWindow", "ОЧИСТИТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_disciplines), _translate("MainWindow", "ДИСЦИПЛИНЫ"))
        self.label_head_teachers.setText(_translate("MainWindow", "СПИСОК ПРЕПОДАВАТЕЛЕЙ"))
        self.label_update_teachers.setText(_translate("MainWindow", "ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: %s"))
        self.button_update_teachers.setText(_translate("MainWindow", "ОБНОВИТЬ"))
        self.button_gen_teachers.setText(_translate("MainWindow", "ГЕНЕРАЦИЯ"))
        self.button_add_teachers.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.button_edit_teachers.setText(_translate("MainWindow", "ИЗМЕНИТЬ"))
        self.button_delete_teachers.setText(_translate("MainWindow", "УДАЛИТЬ"))
        self.button_clear_teachers.setText(_translate("MainWindow", "ОЧИСТИТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_teachers), _translate("MainWindow", "ПРЕПОДАВАТЕЛИ"))
